In [1]:
from producecfg import *
from libSOGA import *

from time import time

num_rep = 10

# Comparison with state-of-the-art

## Bernoulli

true value: 0.25

In [2]:
start = time()
cfg = produce_cfg('Bernoulli')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.024992704391479492


In [3]:
cfg.ID_list

['theta', 'y']

In [4]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  15.051467609405517
N. components: 1774


array([0.25191365, 1.        ])

### Pruning

In [5]:
start = time()
cfg = produce_cfg('BernoulliPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.012492895126342773


In [6]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  1.7378114223480225
N. components: 27


array([0.25191323, 1.        ])

In [7]:
0.015*1774

26.61

## BayesPointMachine

true value: 0.056

In [8]:
start = time()
cfg = produce_cfg('BayesPointMachine')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.03166985511779785


In [9]:
cfg.ID_list

['w[0]',
 'w[1]',
 'w[2]',
 'mean[0]',
 'mean[1]',
 'mean[2]',
 'mean[3]',
 'mean[4]',
 'mean[5]']

In [10]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

mean = output_dist.gm.mean()

Computation completed in  2.534773659706116
N. components: 1


In [11]:
mean[0]

0.01117729116231203

## Burglar

exact

In [12]:
start = time()
cfg = produce_cfg('Burglar')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.023955583572387695


In [13]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['earthquake', 'burglary', 'alarm', 'phoneWorking', 'maryWakes', 'called']
#vars: 6


In [14]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Computation completed in  0.019631218910217286
N. components: 4


0.0029934492413055433

## ClickGraph

true value: 0.614154

In [15]:
start = time()
cfg = produce_cfg('ClickGraph')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.02008223533630371


In [16]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['simAll', 'sim', 'beta1', 'beta2', 'click0', 'click1']
#vars: 6


In [17]:
# goes timeout > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [18]:
start = time()
cfg = produce_cfg('ClickGraphPrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01664137840270996


In [19]:
cfg.ID_list

['simAll', 'sim', 'beta1', 'beta2', 'click0', 'click1']

In [20]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  221.97202715873718
N. components: 35


0.6296009102280258

In [21]:
0.015*2304

34.56

## ClinicalTrial2

true value: 0.754902

In [22]:
cfg = produce_cfg('ClinicalTrial2')

In [23]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']
#vars: 5


In [24]:
# goes time out > 30 min

#start = time()
#output_dist = start_SOGA(cfg)
#end = time()

#print('Computation completed in ', end-start)

#output_dist.gm.mean()

### Pruning

In [25]:
start = time()
cfg = produce_cfg('ClinicalTrial2Prune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.014215946197509766


In [26]:
cfg.ID_list

['isEff', 'probTreated', 'probContr', 'ycontr', 'ytreat']

In [27]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  91.28812527656555
N. components: 23


0.7530902888328648

In [28]:
0.015*1508

22.619999999999997

## CoinBias

true value: 0.417

In [29]:
start = time()
cfg = produce_cfg('CoinBias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.009124755859375


In [30]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['bias', 'y']
#vars: 2


In [31]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.43610968589782717
N. components: 64


array([0.41545796, 0.        ])

## Digit

true value ?

In [32]:
start = time()
cfg = produce_cfg('DigitRecognition')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.14521479606628418


In [33]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y', 'dig']
#vars: 2


In [34]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))

output_dist.gm.mean()[0]

Computation completed in  4.670059871673584


4.4539341842632565

In [35]:
output_dist.gm.n_comp()

10

## Grass

exact

In [36]:
start = time()
cfg = produce_cfg('Grass')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.02372002601623535


In [37]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['cloudy', 'rain', 'sprinkler', 'temp1', 'wetRoof', 'temp2', 'temp3', 'or1', 'or2', 'wetGrass']
#vars: 10


In [38]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[1]

Computation completed in  0.050975584983825685
N. components: 28


0.7079276773296245

In [39]:
509/719

0.7079276773296245

## MurderMistery

exact

In [40]:
start = time()
cfg = produce_cfg('MurderMistery')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [41]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['aliceDunnit', 'withGun']
#vars: 2


In [42]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.003114199638366699
N. components: 2


array([0.01581722, 1.        ])

## NoisyOr

exact

In [43]:
start = time()
cfg = produce_cfg('NoisyOr')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015539169311523438


In [44]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['n0', 'n4', 'n1', 'n21', 'n22', 'n33', 'n2', 'n31', 'n32', 'n3']
#vars: 10


In [45]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.12399206161499024
N. components: 256


0.8144187499999991

## SurveyUnbias

true value: 0.8

In [46]:
start = time()
cfg = produce_cfg('SurveyUnbias')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [47]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['bias1', 'bias2', 'ansb1', 'ansb2']
#vars: 4


In [48]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[0]

Computation completed in  1.3916194677352904
N. components: 128


0.7987653829530976

## TrueSkill

In [49]:
start = time()
cfg = produce_cfg('TrueSkill')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.012816429138183594


In [50]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['skillA', 'skillB', 'skillC', 'perfA', 'perfB', 'perfC']
#vars: 6


In [51]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.04332411289215088
N. components: 1


array([104.71317347,  97.6098938 ,  97.67694092, 115.3177955 ,
        92.23214722,  92.45005919])

## TwoCoins

exact

In [52]:
start = time()
cfg = produce_cfg('TwoCoins')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [53]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['first', 'second', 'both']
#vars: 3


In [54]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.004674983024597168
N. components: 3


array([0.33333333, 0.33333333, 0.        ])

## Altermu

true value: 
mu1: 3.365363543395006e-16

In [55]:
start = time()
cfg = produce_cfg('AQUA/Altermu')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.003014087677001953


In [56]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'w1', 'w2', 'w3', 'mean']
#vars: 44


In [57]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-4:-1]

Computation completed in  0.12872681617736817
N. components: 1


array([ 0.        ,  0.        , -0.00137427], dtype=float32)

## Altermu2

true value:
mu1:  0.15521420874071362
mu2:  0.1552142087407135

In [58]:
start = time()
cfg = produce_cfg('AQUA/Altermu2')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015480518341064453


In [59]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'w1', 'w2']
#vars: 42


In [60]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-2:]

Computation completed in  0.31998391151428224
N. components: 4


array([0.15558612, 0.15558612], dtype=float32)

## Normal Mixtures

In [61]:
start = time()
cfg = produce_cfg('AQUA/NormalMixture')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01883673667907715


In [62]:
# goes t.o. > 30 min even with pruning

#times = []
#
#start = time()
#output_dist = start_SOGA(cfg)
#end = time()
#times.append(end-start)
#
#print('Computation completed in ', np.mean(times))
#
#output_dist.gm.mean()

### Pruning

In [63]:
start = time()
cfg = produce_cfg('AQUA/NormalMixturePrune')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.012033224105834961


In [64]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['theta', 'mu1', 'mu2', 'y']
#vars: 4


In [65]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)

print('Computation completed in ', np.mean(times))

output_dist.gm.mean()

Computation completed in  52.615823125839235


array([ 0.2982786,  3.6915321,  4.8735046, 10.624819 ], dtype=float32)

In [66]:
output_dist.gm.n_comp()

30

In [67]:
30/97714

0.00030701844157439054

## RadarQuery

In [68]:
start = time()
cfg = produce_cfg('AQUA/RadarQuery')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.022469282150268555


In [69]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['b0', 'b1', 'x0', 'x1', 'x', 'y', 'o0', 'o1']
#vars: 8


In [70]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  7.031669616699219
N. components: 2016


array([ 0.9999916 ,  0.9999916 ,  5.940395  ,  5.940395  , -1.6595752 ,
        0.33188623,  4.999984  ,  4.6127315 ], dtype=float32)

## TimeSeries

true value 
alpha:  -1.5751952024094684
beta:  0.6841150519335847
lambda:  0.4765771501058374

In [71]:
start = time()
cfg = produce_cfg('AQUA/TimeSeries')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.08223414421081543


In [72]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['a', 'b', 'lamb', 'y0', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6', 'y7', 'y8', 'y9', 'y10', 'y11', 'y12', 'y13', 'y14', 'y15', 'y16', 'y17', 'y18', 'y19', 'y20', 'y21', 'y22', 'y23', 'y24', 'y25', 'y26', 'y27', 'y28', 'y29', 'y30', 'y31', 'y32', 'y33', 'y34', 'y35', 'y36', 'y37', 'y38', 'y39']
#vars: 43


In [73]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[:3]

Computation completed in  0.8974315881729126
N. components: 8


array([-1.6015656,  0.695174 ,  0.4535055], dtype=float32)

# Mixtures of Continuous and Discrete Distributions

## Indian GPA

true value: 1

In [74]:
start = time()
cfg = produce_cfg('IndianGPA')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0142974853515625


In [75]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['usa', 'usagpa', 'indgpa', 'gpa']
#vars: 4


In [76]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.08550360202789306
N. components: 11


array([1.        , 4.        , 5.12034045, 4.        ])

## Scale

true value: 0

In [77]:
start = time()
cfg = produce_cfg('Scale')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0048673152923583984


In [78]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['hasFake', 'wFake', 'balance']
#vars: 3


In [79]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()

Computation completed in  0.007857394218444825
N. components: 1


array([0.        , 0.61848015, 0.        ])

## Tracking1

In [80]:
start = time()
cfg = produce_cfg('Tracking/Tracking1')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015586376190185547


In [81]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['x', 'y', 'distx', 'disty', 'dist', 'out', 'observed']
#vars: 7


In [82]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.026749420166015624
N. components: 1


10.0

## Tracking5

In [83]:
start = time()
cfg = produce_cfg('Tracking/Tracking5')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.015603065490722656


In [84]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['x', 'y', 'distx', 'disty', 'dist', 'out', 'observed']
#vars: 7


In [85]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.031394004821777344
N. components: 1


10.0

## Tracking10

In [86]:
start = time()
cfg = produce_cfg('Tracking/Tracking10')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.006087541580200195


In [87]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['x', 'y', 'distx', 'disty', 'dist', 'out', 'observed']
#vars: 7


In [88]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.04098224639892578
N. components: 1


10.0

## Tracking50

In [89]:
start = time()
cfg = produce_cfg('Tracking/Tracking50')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0


In [90]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['x', 'y', 'distx', 'disty', 'dist', 'out', 'observed']
#vars: 7


In [91]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.1101496696472168
N. components: 1


10.0

## Tracking100

In [92]:
start = time()
cfg = produce_cfg('Tracking/Tracking100')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.00500941276550293


In [93]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['x', 'y', 'distx', 'disty', 'dist', 'out', 'observed']
#vars: 7


In [94]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.18774197101593018
N. components: 1


10.0

## Tracking150

In [95]:
start = time()
cfg = produce_cfg('Tracking/Tracking150')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0032567977905273438


In [96]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['x', 'y', 'distx', 'disty', 'dist', 'out', 'observed']
#vars: 7


In [97]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.26726398468017576
N. components: 1


10.0

# Collaborative FIltering

## Collaborative Filtering 1

In [98]:
start = time()
cfg = produce_cfg('Collaborative Filtering/CF1')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.01648569107055664


In [99]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'a', 'b', 'c', 'mean']
#vars: 44


In [100]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.14788496494293213
N. components: 1


1.8645055

## Collaborative Filtering 2

In [101]:
start = time()
cfg = produce_cfg('Collaborative Filtering/CF2')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.018189430236816406


In [102]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'a1', 'b1', 'a2', 'b2', 'c', 'mean1', 'mean2', 'mean']
#vars: 48


In [103]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.16290671825408937
N. components: 1


24.282717

## Collaborative Filtering 3

In [104]:
start = time()
cfg = produce_cfg('Collaborative Filtering/CF3')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.016040325164794922


In [105]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'a1', 'b1', 'a2', 'b2', 'a3', 'b3', 'c', 'mean1', 'mean2', 'mean3', 'mean']
#vars: 51


In [106]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.17109014987945556
N. components: 1


-5.7909393

## Collaborative Filtering 5

In [107]:
start = time()
cfg = produce_cfg('Collaborative Filtering/CF5')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0255279541015625


In [108]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'a1', 'b1', 'a2', 'b2', 'a3', 'b3', 'a4', 'b4', 'a5', 'b5', 'c', 'mean1', 'mean2', 'mean3', 'mean4', 'mean5', 'mean']
#vars: 57


In [109]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.20020630359649658
N. components: 1


-31.984488

## Collaborative Filtering 10

In [110]:
start = time()
cfg = produce_cfg('Collaborative Filtering/CF10')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.03332853317260742


In [111]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'a1', 'b1', 'a2', 'b2', 'a3', 'b3', 'a4', 'b4', 'a5', 'b5', 'a6', 'b6', 'a7', 'b7', 'a8', 'b8', 'a9', 'b9', 'a10', 'b10', 'c', 'mean1', 'mean2', 'mean3', 'mean4', 'mean5', 'mean6', 'mean7', 'mean8', 'mean9', 'mean10', 'mean']
#vars: 72


In [112]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.2711367607116699
N. components: 1


149.75401

## Collaborative Filtering 20

In [113]:
start = time()
cfg = produce_cfg('Collaborative Filtering/CF20')
end = time()

print('Time to produce cfg: ', end-start)

Time to produce cfg:  0.0447385311126709


In [114]:
print(cfg.ID_list)
print('#vars:', len(cfg.ID_list))

['y[0]', 'y[1]', 'y[2]', 'y[3]', 'y[4]', 'y[5]', 'y[6]', 'y[7]', 'y[8]', 'y[9]', 'y[10]', 'y[11]', 'y[12]', 'y[13]', 'y[14]', 'y[15]', 'y[16]', 'y[17]', 'y[18]', 'y[19]', 'y[20]', 'y[21]', 'y[22]', 'y[23]', 'y[24]', 'y[25]', 'y[26]', 'y[27]', 'y[28]', 'y[29]', 'y[30]', 'y[31]', 'y[32]', 'y[33]', 'y[34]', 'y[35]', 'y[36]', 'y[37]', 'y[38]', 'y[39]', 'a1', 'b1', 'a2', 'b2', 'a3', 'b3', 'a4', 'b4', 'a5', 'b5', 'a6', 'b6', 'a7', 'b7', 'a8', 'b8', 'a9', 'b9', 'a10', 'b10', 'a11', 'b11', 'a12', 'b12', 'a13', 'b13', 'a14', 'b14', 'a15', 'b15', 'a16', 'b16', 'a17', 'b17', 'a18', 'b18', 'a19', 'b19', 'a20', 'b20', 'c', 'mean1', 'mean2', 'mean3', 'mean4', 'mean5', 'mean6', 'mean7', 'mean8', 'mean9', 'mean10', 'mean11', 'mean12', 'mean13', 'mean14', 'mean15', 'mean16', 'mean17', 'mean18', 'mean19', 'mean20', 'mean']
#vars: 102


In [115]:
times = []

for i in range(num_rep):
    start = time()
    output_dist = start_SOGA(cfg)
    end = time()
    times.append(end-start)
    
print('Computation completed in ', np.mean(times))
print('N. components:', output_dist.gm.n_comp())

output_dist.gm.mean()[-1]

Computation completed in  0.5601183176040649
N. components: 1


73.76569